[project]
name = "sdg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fugashi[unidic-lite]>=1.5.1",
    "ollama>=0.5.2",
    "pandas>=2.3.1",
    "sentence-transformers>=5.1.0",
    "vllm>=0.10.0",
    "wordfreq>=3.1.1",
]
